Combining all data files for a single season together

In [1]:
import csv
import pandas as pd
import os
route_Dir = r'C:\Users\jacks\OneDrive\Documents\Work\Football\Datasets\StatsBomb\2020-21\\'

In [2]:
def normalise_Data_File(data_file,column_headers):
    df = pd.read_csv(route_Dir+data_file, encoding="ISO-8859-1")
    df = df.iloc[1: , :]
    df.columns = column_headers
    del df['Matches']
    print(data_file+' Complete')
    return df

In [3]:
standardStats_column_headers=['Rk','Player','Nation','Pos','Squad','Age','Born',
                            'MP','Starts','Min','90s',
                            'Gls', 'Ast','G-PK','PK','PKatt','CrdY','CrdR',
                            'Gls/90','Ast/90','G+A/90','G-PK/90','G+A-PK/90',
                            'xG','npxG','xA','npxG+xA',
                            'xG/90','xA/90','xG+xA/90', 'npxG/90','npxG+xA/90',
                            'Matches'
                ]

df_standardStats = normalise_Data_File('Standard Stats.csv',standardStats_column_headers)

goalkeepingStats_column_headers = ['Rk','Player','Nation','Pos','Squad','Age','Born',
                                    'MP','Starts','Min','90s',
                                    'GA','GA90','SoTA','Saves','Save%',
                                    'W','D','L',
                                    'CS','CS%','PKatt','PKA','PKsv','PKm','Save%PK',
                                    'Matches'
]

df_goalkeepingStats = normalise_Data_File('Goalkeeping Stats.csv',goalkeepingStats_column_headers)

AdvGoalkeeping_column_headers = ['Rk','Player','Nation','Pos','Squad','Age','Born',
                                '90s','GA','PKA','FK','CK','OG',
                                'PSxG','PSxG/SoT','PSxG+/-','/90',
                                'Cmp','Att','Cmp%',
                                'Att','Thr','Launch%','AvgLen',
                                'AttGK','Launch%GK','AvgLenGK',
                                'Opp','Stp','Stp%',
                                '#OPA','#OPA/90','AvgDist',
                                'Matches']

df_AdvGoalkeepingStats = normalise_Data_File('Advanced Goalkeeping Stats.csv',AdvGoalkeeping_column_headers)

shooting_column_headers = [ 'Rk','Player','Nation','Pos','Squad','Age','Born',
                            '90s','Gls','Sh','SoT','SoT%','Sh/90','SoT/90','G/Sh','G/SoT','Dist','FK',
                            'PK','PKatt',
                            'xG','npxG','npxG/Sh','G-xG','np:G-xG',
                            'Matches'

]

df_shootingStats = normalise_Data_File('Shooting Stats.csv',shooting_column_headers)

passing_column_headers=['Rk','Player','Nation','Pos','Squad','Age','Born',
                        '90s','TotCmp','TotAtt','TotCmp%','TotDist','PrgDist',
                        'SrtCmp','SrtAtt','SrtCmp%',
                        'MedCmp','MedAtt','MedCmp%',
                        'LngCmp','LngAtt','LngCmp%',
                        'Ast','xA','A-xA','KP','P3rd','PPA','CrsPA','Prog',
                        'Matches'
]

df_passingStats = normalise_Data_File('Passing Stats.csv',passing_column_headers)

passingTypes_column_headers=['Rk','Player','Nation','Pos','Squad','Age','Born',
                            '90s','Att','Live','Dead','FK','TB','Press','Sw','Crs','CK',
                            'InCK','OutCK','StrCK',
                            'Ground','Low','High',
                            'LeftBP','RightBP','HeadBP','TIBP','OtherBP',
                            'Cmp','OffOC','OutOC','IntOC','BlocksOC',
                            'Matches'

]

df_passTypes = normalise_Data_File('Passing Types Stats.csv',passingTypes_column_headers)

GoalandShotCreation_column_headers=['Rk','Player','Nation','Pos','Squad','Age','Born',
                            '90s','SCA','SCA90','PassLive','PassDead',
                            'Drib','Sh2sh','Fld','Def','GCA','GCA90','PassLiveG','PassDeadG','DribG','ShG','FldG','DefG',
                            'Matches'
]

df_GoalandShotCreation = normalise_Data_File('Goal and Shot Creating Stats.csv',GoalandShotCreation_column_headers)

DefensiveActions_column_headers=['Rk','Player','Nation','Pos','Squad','Age','Born',
                            '90s','Tkl','TklW','Def 3rd','Mid 3rd','Att 3rd',
                            'TklDbl','AttDbl','Tkl%Dbl','PastDbl',
                            'Press','PressSucc','Press%','PressDef3rd','PressMid3rd','PressAtt3rd',
                            'Blocks','ShBlocks','ShSvBlocks','PassBlocks',
                            'Int','Tkl_Int','Clr','Err',
                            'Matches'
]

df_DefensiveActions = normalise_Data_File('Defensive Actions Stats.csv',DefensiveActions_column_headers)

PlayingTime_column_headers=['Rk','Player','Nation','Pos','Squad','Age','Born',
                            'MP','Min','Mn/MP','Min%','90s','Starts',
                            'Mn/Start','Compl','Subs','Mn/Sub','unSub',
                            'PPM','onG','onGA','+/-','+/-90','On-Off','onxG','onxGA','xG+/-','xG+/-90','On-Off',
                            'Matches'
]

df_PlayingTime = normalise_Data_File('Playing Time Stats.csv',PlayingTime_column_headers)

Miscellaneous_column_headers=['Rk','Player','Nation','Pos','Squad','Age','Born',
                            '90s','CrdY','CrdR','2CrdY','Fls','Fld','Off','Crs','Int','TklW',
                            'Pkwon','PKcon','OG','Recov','Won','Lost','Won%',
                            'Matches'
]

df_Miscellaneous = normalise_Data_File('Miscellaneous Stats.csv',Miscellaneous_column_headers)

Standard Stats.csv Complete
Goalkeeping Stats.csv Complete
Advanced Goalkeeping Stats.csv Complete
Shooting Stats.csv Complete
Passing Stats.csv Complete
Passing Types Stats.csv Complete
Goal and Shot Creating Stats.csv Complete
Defensive Actions Stats.csv Complete
Playing Time Stats.csv Complete
Miscellaneous Stats.csv Complete

In [4]:
#print(len(df_AdvGoalkeepingStats))
#print(len(df_goalkeepingStats))
#print(len(df_PlayingTime))

dfs_toMerge = [df_shootingStats,df_passTypes,df_passingStats,df_GoalandShotCreation,df_DefensiveActions,df_Miscellaneous]
df_PlayerStats20_21 = df_standardStats

for df in dfs_toMerge:
    del df['Rk'],df['Player'], df['Nation'],df['Pos'],df['Squad'],df['Age'],df['Born'],df['90s']
    df_PlayerStats20_21 = pd.concat([df_PlayerStats20_21, df], axis=1, join="inner")

df_PlayerStats20_21.to_csv(route_Dir+'Combined Data.csv',index=False)
df_PlayerStats20_21

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,Crs,Int,TklW,Pkwon,PKcon,OG,Recov,Won,Lost,Won%
1,1,Patrick van Aanholt\5f09991f,nl NED,DF,Crystal Palace,29,1990,22,20,1777,...,34,34,19,0,0,0,179,10,11,47.6
2,2,Tammy Abraham\f586779e,eng ENG,FW,Chelsea,22,1997,22,12,1040,...,4,2,4,1,0,0,47,39,28,58.2
3,3,Che Adams\f2bf1b0f,sct SCO,FW,Southampton,24,1996,36,30,2667,...,13,11,17,0,0,0,119,47,141,25.0
4,4,Tosin Adarabioyo\c81d773d,eng ENG,DF,Fulham,22,1997,33,33,2953,...,3,55,26,0,1,1,278,100,39,71.9
5,5,AdriÃ¡n\f76e6b4e,es ESP,GK,Liverpool,33,1987,3,3,270,...,0,0,0,0,0,0,20,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,528,Andi Zeqiri\d01231f0,ch SUI,FWDF,Brighton,21,1999,9,0,171,...,5,0,3,0,0,0,12,2,5,28.6
529,529,Oleksandr Zinchenko\51cf8561,ua UKR,DF,Manchester City,23,1996,20,15,1478,...,17,20,13,0,0,0,153,24,14,63.2
530,530,Hakim Ziyech\6622454d,ma MAR,FWMF,Chelsea,27,1993,23,15,1172,...,42,10,7,0,0,0,94,3,22,12.0
531,531,Kurt Zouma\ce4246f5,fr FRA,DF,Chelsea,25,1994,24,22,2029,...,0,26,13,0,0,0,210,97,34,74.0
532,532,Martin Ãdegaard\79300479,no NOR,MF,Arsenal,21,1998,14,9,866,...,12,5,5,0,0,0,56,1,14,6.7

Collate combined datasets for each season into a single dataframe

Left joins on the latest season so will only contain players who played in the latest season

In [36]:
folderDir = r'C:\Users\jacks\OneDrive\Documents\Work\Football\Datasets\StatsBomb\\'
#folders = os.listdir(folderDir) #manual to ensure order is probably best practice
folders = ['2020-21','2017-18']

df_combined = pd.read_csv(folderDir+folders[0]+'\\Combined Data.csv', encoding="ISO-8859-1").add_prefix('y'+folders[0]+'_')
df_combined.columns.values[1] = "Player"
df_combined = df_combined.set_index('Player')

for folder in folders[1:]:
    df = pd.read_csv(folderDir+folder+'\\Combined Data.csv', encoding="ISO-8859-1").add_prefix('y'+folder+'_')
    df.columns.values[1] = "Player"
    df = df.set_index('Player')
    df_combined = df_combined.join(df)

df_combined

,y2020-21_Rk,y2020-21_Nation,y2020-21_Pos,y2020-21_Squad,y2020-21_Age,y2020-21_Born,y2020-21_MP,y2020-21_Starts,y2020-21_Min,y2020-21_90s,...,y2017-18_Crs.1,y2017-18_Int.1,y2017-18_TklW.1,y2017-18_Pkwon,y2017-18_PKcon,y2017-18_OG,y2017-18_Recov,y2017-18_Won,y2017-18_Lost,y2017-18_Won%
Player,,,,,,,,,,,,,,,,,,,,,
Aaron Connolly\27c01749,104,ie IRL,FW,Brighton,20,2000,17,9,791,8.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aaron Cresswell\4f974391,110,eng ENG,DF,West Ham,30,1989,36,36,3170,35.2,...,93.0,52.0,18.0,0.0,0.0,0.0,277.0,69.0,57.0,54.8
Aaron Ramsdale\466fb2c5,386,eng ENG,GK,Sheffield Utd,22,1998,38,38,3420,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aaron Wan-Bissaka\9e525177,502,eng ENG,DF,Manchester Utd,22,1997,34,34,3060,34.0,...,13.0,13.0,18.0,0.0,0.0,0.0,49.0,10.0,11.0,47.6
Abdoulaye DoucourÃÂ©\02b29014,137,fr FRA,MF,Everton,27,1993,29,29,2443,27.1,...,24.0,67.0,55.0,0.0,1.0,0.0,554.0,64.0,61.0,51.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zack Steffen\42130443,453,us USA,GK,Manchester City,25,1995,1,1,90,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ÃÂaÃÂlar SÃÂ¶yÃÂ¼ncÃÂ¼\21166ff4,452,tr TUR,DF,Leicester City,24,1996,23,19,1819,20.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ÃÂrik Lamela\abe66106,259,ar ARG,FWMF,Tottenham,28,1992,23,5,717,8.0,...,10.0,8.0,17.0,1.0,0.0,0.0,58.0,8.0,24.0,25.0
ÃÂ°lkay GÃÂ¼ndoÃÂan\819b3158,190,de GER,MF,Manchester City,29,1990,28,23,2029,22.5,...,8.0,21.0,21.0,0.0,0.0,0.0,126.0,4.0,14.0,22.2
Ã Âukasz FabiaÃ Âski\9328b835,150,pl POL,GK,West Ham,35,1985,35,35,3150,35.0,...,0.0,0.0,0.0,0.0,0.0,0.0,172.0,0.0,1.0,0.0

In [6]:
df_combined.to_csv(r'C:\Users\jacks\OneDrive\Documents\Work\Football\Datasets\StatsBomb\collatedData17-20.csv')

Analysis

In [7]:
#create a new working dataframe
df = df_combined
#remove rows where there is no 2017-18 data
df = df[df['y2017-18_Won%'].notna()]
print(len(df))

221

In [16]:
import pandas as pd

df = pd.read_csv(r'C:\Users\jacks\OneDrive\Documents\Work\Football\Datasets\StatsBomb\collatedData17-20.csv')
#df_combined = df
#df_combined

In [17]:

#print('Number of players with data from 2017/18: ',len(df.loc[df['y2017-18_Rk'].notnull()]))   
#print(df['y2017-18_Pos'].value_counts())

print('Number of players in with position MF, with data from 2017-18, and 2020-21')
print(df[((df['y2017-18_Pos'].notnull()) & (df['y2020-21_Pos'] =='MF'))]['y2017-18_Pos'].value_counts())

#print('Number of players with data from 2018/19: ',len(df.loc[df['y2018-19_Rk'].notnull()]))
#print(df['y2018-19_Pos'].value_counts())
#print('Number of players with data from 2019/20: ',len(df.loc[df['y2019-20_Rk'].notnull()]))
#print(df['y2019-20_Pos'].value_counts())
#print('Number of players with data from 2020/21: ',len(df.loc[df['y2020-21_Rk'].notnull()]))
#print(df['y2020-21_Pos'].value_counts())

Number of players in with position MF, with data from 2017-18, and 2020-21
MF      29
MFFW     7
DFMF     3
MFDF     2
FWMF     1
Name: y2017-18_Pos, dtype: int64

Create Dataframe containing player data from just the years 17/18 and 20/21.

Filter this further to Just those in the forward positions

In [18]:
roles=['FW','FWDF','FWMF','MFFW']
df_17_20_FW = df_combined[((df_combined['y2017-18_Pos'].notnull()) & (df_combined['y2020-21_Pos'].isin(roles)))]
df_17_20_FW

,Player,y2020-21_Rk,y2020-21_Nation,y2020-21_Pos,y2020-21_Squad,y2020-21_Age,y2020-21_Born,y2020-21_MP,y2020-21_Starts,y2020-21_Min,...,y2017-18_Crs.1,y2017-18_Int.1,y2017-18_TklW.1,y2017-18_Pkwon,y2017-18_PKcon,y2017-18_OG,y2017-18_Recov,y2017-18_Won,y2017-18_Lost,y2017-18_Won%
6,Adam Lallana\99813635,258,eng ENG,MFFW,Brighton,32,1988,30,16,1596,...,6.0,5.0,3.0,0.0,0.0,0.0,32.0,3.0,6.0,33.3
9,Ademola Lookman\7c104bb7,281,eng ENG,FWMF,Fulham,22,1997,34,31,2747,...,0.0,2.0,2.0,0.0,0.0,0.0,16.0,1.0,1.0,50.0
15,Aleksandar MitroviÃÂ\3925dbd6,329,rs SRB,FW,Fulham,25,1994,27,13,1402,...,1.0,1.0,0.0,0.0,0.0,0.0,9.0,4.0,9.0,30.8
16,Alex Iwobi\6ca5ec4b,216,ng NGA,FWDF,Everton,24,1996,30,17,1542,...,29.0,12.0,21.0,0.0,0.0,0.0,149.0,7.0,21.0,25.0
18,Alex Oxlade-Chamberlain\38c7feef,364,eng ENG,FWMF,Liverpool,26,1993,13,2,253,...,40.0,20.0,23.0,0.0,0.0,0.0,153.0,16.0,31.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,Theo Walcott\1ecb65be,499,eng ENG,FW,Everton,31,1989,1,0,13,...,40.0,14.0,12.0,0.0,0.0,0.0,100.0,8.0,29.0,21.6
525,Wilfried Zaha\b2bc3b1f,526,ci CIV,FW,Crystal Palace,27,1992,30,29,2612,...,85.0,19.0,24.0,4.0,0.0,0.0,186.0,2.0,49.0,3.9
530,Willian\8b9ebd03,516,br BRA,FWMF,Arsenal,31,1988,25,16,1406,...,51.0,12.0,24.0,1.0,0.0,0.0,142.0,11.0,23.0,32.4
533,Xherdan Shaqiri\6421ec64,435,ch SUI,MFFW,Liverpool,28,1991,14,5,556,...,101.0,30.0,16.0,0.0,0.0,0.0,209.0,10.0,32.0,23.8
540,ÃÂrik Lamela\abe66106,259,ar ARG,FWMF,Tottenham,28,1992,23,5,717,...,10.0,8.0,17.0,1.0,0.0,0.0,58.0,8.0,24.0,25.0

Label the Rows.
At the moment it is very simple: 8 goals or over is a 1.

This is a first attempt, so is simple by design

In [19]:
pd.options.mode.chained_assignment = None  # default='warn'
def calc_label(row):
    if row['y2020-21_Gls'] < 8:
        value = 0
    else:
        value = 1
    return value

df_17_20_FW['label'] = df_17_20_FW.apply(calc_label, axis=1)
df_17_20_FW['label'].value_counts()

0    55
1    23
Name: label, dtype: int64

In [20]:
#df_17_20_FW = df_17_20_FW.iloc[: , 150:]
df_17_20_FW = df_17_20_FW[df_17_20_FW.columns[-150:]]
df_17_20_FW

,y2017-18_Nation,y2017-18_Pos,y2017-18_Squad,y2017-18_Age,y2017-18_Born,y2017-18_MP,y2017-18_Starts,y2017-18_Min,y2017-18_90s,y2017-18_Gls,...,y2017-18_Int.1,y2017-18_TklW.1,y2017-18_Pkwon,y2017-18_PKcon,y2017-18_OG,y2017-18_Recov,y2017-18_Won,y2017-18_Lost,y2017-18_Won%,label
6,eng ENG,MFFW,Liverpool,29.0,1988.0,12.0,1.0,308.0,3.4,0.0,...,5.0,3.0,0.0,0.0,0.0,32.0,3.0,6.0,33.3,0
9,eng ENG,FWMF,Everton,19.0,1997.0,7.0,1.0,159.0,1.8,0.0,...,2.0,2.0,0.0,0.0,0.0,16.0,1.0,1.0,50.0,0
15,rs SRB,FW,Newcastle Utd,22.0,1994.0,6.0,0.0,95.0,1.1,1.0,...,1.0,0.0,0.0,0.0,0.0,9.0,4.0,9.0,30.8,0
16,ng NGA,FWMF,Arsenal,21.0,1996.0,26.0,22.0,1830.0,20.3,3.0,...,12.0,21.0,0.0,0.0,0.0,149.0,7.0,21.0,25.0,0
18,eng ENG,MFFW,Liverpool,23.0,1993.0,32.0,14.0,1493.0,16.6,3.0,...,20.0,23.0,0.0,0.0,0.0,153.0,16.0,31.0,34.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,eng ENG,FW,Everton,28.0,1989.0,14.0,13.0,1152.0,12.8,3.0,...,14.0,12.0,0.0,0.0,0.0,100.0,8.0,29.0,21.6,0
525,ci CIV,FWMF,Crystal Palace,24.0,1992.0,29.0,28.0,2549.0,28.3,9.0,...,19.0,24.0,4.0,0.0,0.0,186.0,2.0,49.0,3.9,1
530,br BRA,FWMF,Chelsea,28.0,1988.0,36.0,20.0,1890.0,21.0,6.0,...,12.0,24.0,1.0,0.0,0.0,142.0,11.0,23.0,32.4,0
533,ch SUI,FWMF,Stoke City,25.0,1991.0,36.0,36.0,3039.0,33.8,8.0,...,30.0,16.0,0.0,0.0,0.0,209.0,10.0,32.0,23.8,0
540,ar ARG,FWMF,Tottenham,25.0,1992.0,25.0,7.0,843.0,9.4,2.0,...,8.0,17.0,1.0,0.0,0.0,58.0,8.0,24.0,25.0,0

In [22]:

df_17_20_FW = df_17_20_FW.drop(['y2017-18_Nation',
                                'y2017-18_Pos',
                                'y2017-18_Squad']
                                ,1)
df_17_20_FW

,y2017-18_Age,y2017-18_Born,y2017-18_MP,y2017-18_Starts,y2017-18_Min,y2017-18_90s,y2017-18_Gls,y2017-18_Ast,y2017-18_G-PK,y2017-18_PK,...,y2017-18_Int.1,y2017-18_TklW.1,y2017-18_Pkwon,y2017-18_PKcon,y2017-18_OG,y2017-18_Recov,y2017-18_Won,y2017-18_Lost,y2017-18_Won%,label
6,29.0,1988.0,12.0,1.0,308.0,3.4,0.0,0.0,0.0,0.0,...,5.0,3.0,0.0,0.0,0.0,32.0,3.0,6.0,33.3,0
9,19.0,1997.0,7.0,1.0,159.0,1.8,0.0,0.0,0.0,0.0,...,2.0,2.0,0.0,0.0,0.0,16.0,1.0,1.0,50.0,0
15,22.0,1994.0,6.0,0.0,95.0,1.1,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,9.0,4.0,9.0,30.8,0
16,21.0,1996.0,26.0,22.0,1830.0,20.3,3.0,5.0,3.0,0.0,...,12.0,21.0,0.0,0.0,0.0,149.0,7.0,21.0,25.0,0
18,23.0,1993.0,32.0,14.0,1493.0,16.6,3.0,7.0,3.0,0.0,...,20.0,23.0,0.0,0.0,0.0,153.0,16.0,31.0,34.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,28.0,1989.0,14.0,13.0,1152.0,12.8,3.0,3.0,3.0,0.0,...,14.0,12.0,0.0,0.0,0.0,100.0,8.0,29.0,21.6,0
525,24.0,1992.0,29.0,28.0,2549.0,28.3,9.0,3.0,9.0,0.0,...,19.0,24.0,4.0,0.0,0.0,186.0,2.0,49.0,3.9,1
530,28.0,1988.0,36.0,20.0,1890.0,21.0,6.0,7.0,5.0,1.0,...,12.0,24.0,1.0,0.0,0.0,142.0,11.0,23.0,32.4,0
533,25.0,1991.0,36.0,36.0,3039.0,33.8,8.0,7.0,8.0,0.0,...,30.0,16.0,0.0,0.0,0.0,209.0,10.0,32.0,23.8,0
540,25.0,1992.0,25.0,7.0,843.0,9.4,2.0,2.0,2.0,0.0,...,8.0,17.0,1.0,0.0,0.0,58.0,8.0,24.0,25.0,0

In [23]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_normalized = pd.DataFrame(scaler.fit_transform(df_17_20_FW), columns= df_17_20_FW.columns)

df_normalized.dropna()
df_normalized

,y2017-18_Age,y2017-18_Born,y2017-18_MP,y2017-18_Starts,y2017-18_Min,y2017-18_90s,y2017-18_Gls,y2017-18_Ast,y2017-18_G-PK,y2017-18_PK,...,y2017-18_Int.1,y2017-18_TklW.1,y2017-18_Pkwon,y2017-18_PKcon,y2017-18_OG,y2017-18_Recov,y2017-18_Won,y2017-18_Lost,y2017-18_Won%,label
0,0.928571,0.142857,0.297297,0.027027,0.092341,0.091667,0.00000,0.000000,0.000000,0.0,...,0.096154,0.047619,0.000000,0.0,0.0,0.125000,0.011494,0.022989,0.333,0.0
1,0.214286,0.785714,0.162162,0.027027,0.046325,0.047222,0.00000,0.000000,0.000000,0.0,...,0.038462,0.031746,0.000000,0.0,0.0,0.062500,0.003831,0.003831,0.500,0.0
2,0.428571,0.571429,0.135135,0.000000,0.026560,0.027778,0.03125,0.000000,0.032258,0.0,...,0.019231,0.000000,0.000000,0.0,0.0,0.035156,0.015326,0.034483,0.308,0.0
3,0.357143,0.714286,0.675676,0.594595,0.562384,0.561111,0.09375,0.454545,0.096774,0.0,...,0.230769,0.333333,0.000000,0.0,0.0,0.582031,0.026820,0.080460,0.250,0.0
4,0.500000,0.500000,0.837838,0.378378,0.458308,0.458333,0.09375,0.636364,0.096774,0.0,...,0.384615,0.365079,0.000000,0.0,0.0,0.597656,0.061303,0.118774,0.340,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,0.857143,0.214286,0.351351,0.351351,0.352996,0.352778,0.09375,0.272727,0.096774,0.0,...,0.269231,0.190476,0.000000,0.0,0.0,0.390625,0.030651,0.111111,0.216,0.0
74,0.571429,0.428571,0.756757,0.756757,0.784435,0.783333,0.28125,0.272727,0.290323,0.0,...,0.365385,0.380952,0.666667,0.0,0.0,0.726562,0.007663,0.187739,0.039,1.0
75,0.857143,0.142857,0.945946,0.540541,0.580914,0.580556,0.18750,0.636364,0.161290,0.2,...,0.230769,0.380952,0.166667,0.0,0.0,0.554688,0.042146,0.088123,0.324,0.0
76,0.642857,0.357143,0.945946,0.972973,0.935763,0.936111,0.25000,0.636364,0.258065,0.0,...,0.576923,0.253968,0.000000,0.0,0.0,0.816406,0.038314,0.122605,0.238,0.0
77,0.642857,0.428571,0.648649,0.189189,0.257566,0.258333,0.06250,0.181818,0.064516,0.0,...,0.153846,0.269841,0.166667,0.0,0.0,0.226562,0.030651,0.091954,0.250,0.0

In [35]:
from sklearn.model_selection import train_test_split
y = df_17_20_FW[['label']]
X = df_normalized.drop(['label'],1)


print('Length of x: ',len(X))
print('Length of y: ',len(y))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

X_test.fillna(X_train.mean(), inplace=True)
X_train.fillna(X_train.mean(), inplace=True)


print('Length of X_train: ',len(X_train))
print('Length of X_test: ',len(X_test))
print('Length of y_train: ',len(y_train))
print('Length of y_test: ',len(y_test))

Length of x:  78
Length of y:  78
Length of X_train:  54
Length of X_test:  24
Length of y_train:  54
Length of y_test:  24

In [25]:
df_normalized.dtypes

y2017-18_Age       float64
y2017-18_Born      float64
y2017-18_MP        float64
y2017-18_Starts    float64
y2017-18_Min       float64
                    ...
y2017-18_Recov     float64
y2017-18_Won       float64
y2017-18_Lost      float64
y2017-18_Won%      float64
label              float64
Length: 147, dtype: object

SVM Classifier

In [26]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[13  1]
 [ 6  4]]
              precision    recall  f1-score   support

           0       0.68      0.93      0.79        14
           1       0.80      0.40      0.53        10

    accuracy                           0.71        24
   macro avg       0.74      0.66      0.66        24
weighted avg       0.73      0.71      0.68        24

c:\Users\jacks\env\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
RFclassifier = RandomForestClassifier()
RFclassifier.fit(X_train, y_train)

y_pred = RFclassifier.predict(X_test)


print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

out = y_test
out['pred'] = y_pred
out

c:\Users\jacks\env\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

[[13  1]
 [ 5  5]]
              precision    recall  f1-score   support

           0       0.72      0.93      0.81        14
           1       0.83      0.50      0.62        10

    accuracy                           0.75        24
   macro avg       0.78      0.71      0.72        24
weighted avg       0.77      0.75      0.73        24

     label  pred
399      0     0
422      1     1
75       0     0
192      1     0
22       1     1
453      0     0
364      1     1
459      1     1
230      1     1
90       1     0
19       0     0
291      1     0
450      0     0
395      0     0
396      0     0
376      0     0
84       0     0
18       0     0
244      1     0
433      0     1
421      1     0
449      0     0
48       0     0
9        0     0

Naive Bayes

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

c:\Users\jacks\env\lib\site-packages\sklearn\naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [40]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[15  1]
 [ 4  4]]
              precision    recall  f1-score   support

           0       0.79      0.94      0.86        16
           1       0.80      0.50      0.62         8

    accuracy                           0.79        24
   macro avg       0.79      0.72      0.74        24
weighted avg       0.79      0.79      0.78        24

K nearest Neighbour

In [60]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=2)
neigh.fit(X_train, y_train)

c:\Users\jacks\env\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [61]:
y_pred = neigh.predict(X_test)

In [62]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[14  2]
 [ 7  1]]
              precision    recall  f1-score   support

           0       0.67      0.88      0.76        16
           1       0.33      0.12      0.18         8

    accuracy                           0.62        24
   macro avg       0.50      0.50      0.47        24
weighted avg       0.56      0.62      0.57        24